### ISSUE TITLE
Adding Books

### ISSUE THREAD

**Issue by DarshGupta1910** [Jassi10000/LGM-SOC-21#4]
Since there are only videos added in the resources, I'm making a new issue to add some books as well. 

I have found a very useful link that has programming Notes/ Books which we can download for free.  

take a look at this https://goalkicker.com/

**Comment by Jassi10000-zz** [comment]
Thanks  @DarshGupta1910 for this , but for the programme as you  know there's a limited time and the books here have quite good length and thus due to this reason we have wisely chosen the option to put videos instead of documented notes . 
For a beginner to get started with his first contributions , I think a quick tutorial of few hours could help more

Btw you can put this in slack , so that everybody can have access to it .Thanks again for this useful resource

**Comment by DarshGupta1910** [comment]
@Jassi10000 yeah completely agreed with you.

Ok, I will share the notes in slack.

**Comment by Jassi10000-zz** [comment]
> @Jassi10000 yeah completely agreed with you.
> 
> Ok, I will share the notes in slack.

I have done that buddy , also highlighted you for thanksgiving
